spring:
  application:
    name: today-space

  config:
    import: optional:classpath:application-secrets.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGO_DB_URI}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  secret_key: ${JWT_SECRET_KEY}
  expiration:
    access_token: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh_token: ${JWT_REFRESH_TOKEN_EXPIRATION}

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
      baseUrl: https://today-space.s3.ap-northeast-2.amazonaws.com/
    credentials:
      access-key: ${ACCESS_KEY_ID}
      secret-key: ${SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

oauth:
  rest:
    api:
      secret:
        key:
          naver: ${NAVER_REST_API_SECRET_KEY}
          google: ${GOOGLE_REST_API_SECRET_KEY}
      key:
        kakao: ${KAKAO_REST_API_KEY}
        naver: ${NAVER_REST_API_KEY}
        google: ${GOOGLE_REST_API_KEY}




